version: '3.1'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=https://react-learning-course-api.vercel.app
      # - REACT_APP_API_URL=https://localhost:4000
