import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    version: "0.0.1",
    title: "ToDo API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:4000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  definitions: {
    ToDo: {
      text: "task text",
      checked: true,
    },
    ToDoList: [{ $ref: "#/definitions/ToDo" }],
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./endpoints.js"];

swaggerAutogen({ openapi: "3.0.0" })(outputFile, endpointsFiles, doc).then(
  async () => {
    await import("./index.js");
  }
);
